#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : stacer
Version  : 1.1.0
Release  : 2
URL      : https://github.com/oguzhaninan/Stacer/archive/v1.1.0.tar.gz
Source0  : https://github.com/oguzhaninan/Stacer/archive/v1.1.0.tar.gz
Summary  : Ubuntu System Optimizer
Group    : Development/Tools
License  : GPL-3.0 Unlicense
Requires: stacer-bin = %{version}-%{release}
Requires: stacer-data = %{version}-%{release}
Requires: stacer-license = %{version}-%{release}
BuildRequires : buildreq-cmake
BuildRequires : buildreq-qmake
BuildRequires : qtbase-dev mesa-dev
BuildRequires : qtcharts-dev
BuildRequires : qtsvg-dev
BuildRequires : qttools-dev

%description
<p align="center">
<img src="https://raw.githubusercontent.com/oguzhaninan/Stacer/native/screenshots/header.png" width="800">
</p>
<p align="center">
<b>Linux System Optimizer and Monitoring</b>   <br>
<a href="https://www.patreon.com/oguzhaninan">
<img alt="Patreon" src="https://c5.patreon.com/external/logo/become_a_patron_button.png" height="50" />
</a>
<a href="https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=PDMEZXLTSRLHE">
<img src="https://avaazimages.s3.amazonaws.com/paypal_donate_button.jpg" height="50" />
</a>
</p>

%package bin
Summary: bin components for the stacer package.
Group: Binaries
Requires: stacer-data = %{version}-%{release}
Requires: stacer-license = %{version}-%{release}

%description bin
bin components for the stacer package.


%package data
Summary: data components for the stacer package.
Group: Data

%description data
data components for the stacer package.


%package license
Summary: license components for the stacer package.
Group: Default

%description license
license components for the stacer package.


%prep
%setup -q -n Stacer-1.1.0
cd %{_builddir}/Stacer-1.1.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1578329038
mkdir -p clr-build
pushd clr-build
# -Werror is for werrorists
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
%cmake ..
make  %{?_smp_mflags}  VERBOSE=1
popd

%install
export SOURCE_DATE_EPOCH=1578329038
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/stacer
cp %{_builddir}/Stacer-1.1.0/LICENSE %{buildroot}/usr/share/package-licenses/stacer/31a3d460bb3c7d98845187c716a30db81c44b615
cp %{_builddir}/Stacer-1.1.0/cmake/cxxbasics/UNLICENSE %{buildroot}/usr/share/package-licenses/stacer/ff007ce11f3ff7964f1a5b04202c4e95b5c82c85
pushd clr-build
%make_install
popd

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/stacer

%files data
%defattr(-,root,root,-)
/usr/share/applications/stacer.desktop
/usr/share/icons/stacer.png

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/stacer/31a3d460bb3c7d98845187c716a30db81c44b615
/usr/share/package-licenses/stacer/ff007ce11f3ff7964f1a5b04202c4e95b5c82c85
